force-app/main/default/objects/Envelope__c/Envelope__c.object-meta.xml
<CustomObject>
    <label>Envelope</label>
    <nameField>
        <label>Envelope Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Envelopes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Envelope__c/fields/Is_Received__c.field-meta.xml
<CustomField>
    <fullName>Is_Received__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Received</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Envelope__c/fields/Is_Sent__c.field-meta.xml
<CustomField>
    <fullName>Is_Sent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Sent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Envelope__c/fields/Is_Viewed__c.field-meta.xml
<CustomField>
    <fullName>Is_Viewed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Viewed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Envelope__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Envelopes</relationshipLabel>
    <relationshipName>Envelopes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Envelope__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/EmailWebService.cls
@RestResource(urlMapping='/sendmail')
global class EmailWebService {
    @HttpPost
    global static String sendMail() {
        System.debug('php');
        RestRequest req = RestContext.request;
        req.addHeader('accept', 'application/json');
        System.debug('php body: '+req.requestBody.toString());
        String jsonString = req.requestBody.toString();
        String currentUserId = UserInfo.getUserId();
        System.debug('Current User ID: ' + currentUserId);
        
        Map<String, Object> jsonMap = (Map<String, Object>) JSON.deserializeUntyped(jsonString);
		
        System.debug('jsonMap : '+ jsonMap);
        String title = (String) jsonMap.get('Title');
        String conrollId = (String) jsonMap.get('conrollId');
        String usrId = (String) jsonMap.get('usrId');
        String status = (String) jsonMap.get('Status');
        String recordId = (String) jsonMap.get('RecordId');
        String HistoryTrackerId = (String) jsonMap.get('HistoryTrackerId');
        String envelopeId = (String) jsonMap.get('envelopeId');
        String responsneContentVerId = (String) jsonMap.get('uniqueId');
        
        System.debug('responsneContentVerId '+ responsneContentVerId);
        conrollId = conrollId.replaceAll('[()]+', '');
        List<String> idList = conrollId.split(',');
        
        if(Status.containsIgnoreCase('reject')){
            
            
            
            if(envelopeId != Null){
                List<Envelope__c> listOfEnv = [Select Id, Name, Is_received__c, Is_Sent__c, Status__c, Is_Viewed__c, Opportunity__c from Envelope__c Where Id =: envelopeId];
                if(!listOfEnv.isEmpty()){
                	update new Envelope__c(Id=listOfEnv[0].id,Status__c='Rejected');     
                }
            }
            emailToCustomerCtrl.rejectSendEmail(idList, usrId, currentUserId, recordId, HistoryTrackerId, responsneContentVerId);
            
            //customm notification send
            CustomNotificationType notificationType = [ 
                SELECT Id, DeveloperName 
                FROM CustomNotificationType 
                WHERE DeveloperName = 'emailSendOnOpportunity'
            ];
            
            Messaging.CustomNotification notification = new Messaging.CustomNotification();
            
            notification.setTitle('Email Notification');
            notification.setBody('You have received a Mail!');
            notification.setNotificationTypeId(notificationType.Id);
            notification.setTargetId(currentUserId);
            notification.send(new Set<String>{currentUserId});
            
            return req.requestBody.toString();
        }else{
            if(recordId != null){
                	update new quote(Id = recordId, status = 'Accepted');     
            }
            if(envelopeId != Null){
                List<Envelope__c> listOfEnv = [Select Id, Name, Is_received__c, Is_Sent__c, Status__c, Is_Viewed__c, Opportunity__c from Envelope__c Where Id =: envelopeId];
        		update new Envelope__c(Id=listOfEnv[0].id, Status__c='Accepted'); 
            	
                
                //Envelope__c envObj = [Select Id, Name, Is_received__c, Is_Sent__c, Is_Viewed__c, Opportunity__c, Status__c from Envelope__c Where Id =: envelopeId];
            	//envObj.Status__c = 'Accepted';
                //Update envObj;    
            }
            
           emailToCustomerCtrl.reSendEmail(idList, usrId, currentUserId, recordId, HistoryTrackerId, responsneContentVerId);
            
           //
           Quote quoteStage = [SELECT Id, Name, Status,OwnerId,QuoteNumber FROM Quote WHERE Id = : recordId];

           CustomNotificationType notificationType = 
           [SELECT Id, DeveloperName FROM CustomNotificationType WHERE DeveloperName='emailSendOnOpportunity'];
                system.debug('notificationType'+notificationType);
                Messaging.CustomNotification notification = new Messaging.CustomNotification();
       				 //system.debug('recordID'+recordId);
        			//system.debug('userId'+userId);
                notification.setTitle('Email Notification');
                notification.setBody('Your Document has been Accepted');
                notification.setNotificationTypeId(notificationType.Id);
                notification.setTargetId(recordId);
                notification.send(new set<String>{quoteStage.OwnerId});
        system.debug('notification'+notification);
            
            
            
            //customm notification send
            /*CustomNotificationType notificationType = [
                SELECT Id, DeveloperName 
                FROM CustomNotificationType 
                WHERE DeveloperName = 'emailSendOnOpportunity'
            ];
            
            Messaging.CustomNotification notification = new Messaging.CustomNotification();
            
            notification.setTitle('Email Notification');
            notification.setBody('You have received a Mail!');
            notification.setNotificationTypeId(notificationType.Id);
            notification.setTargetId(currentUserId);
            notification.send(new Set<String>{currentUserId});*/
            return req.requestBody.toString();
        }
        //emailToCustomerCtrl.reSendEmail(idList, usrId, currentUserId);
        
        //customm notification send
        /*CustomNotificationType notificationType = [
            SELECT Id, DeveloperName 
            FROM CustomNotificationType 
            WHERE DeveloperName = 'emailSendOnOpportunity'
        ];
       
        Messaging.CustomNotification notification = new Messaging.CustomNotification();
        
        notification.setTitle('Email Notification');
        notification.setBody('You have received a Mail!');
        notification.setNotificationTypeId(notificationType.Id);
        notification.setTargetId(currentUserId);
        notification.send(new Set<String>{currentUserId});
        return req.requestBody.toString();*/
        //return null;
    }
    
    public class MailWrapper {
        public String contactId;
        public String salesrepId;
        public String opportunityId;
        public String body;
    }
}