force-app/main/default/objects/Document_Template__c/Document_Template__c.object-meta.xml
<CustomObject>
    <label>Document Template</label>
    <nameField>
        <label>Document Creator Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Document_Template__c/fields/Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_Name__c</fullName>
    <label>Object Name</label>
    <length>234</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/History_Tracker__c/History_Tracker__c.object-meta.xml
<CustomObject>
    <label>History Tracker</label>
    <nameField>
        <displayFormat>HT-{0000}</displayFormat>
        <label>History Tracker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>History Trackers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/History_Tracker__c/fields/Content_Version__c.field-meta.xml
<CustomField>
    <fullName>Content_Version__c</fullName>
    <label>Content_Version</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/History_Tracker__c/fields/Document_Template__c.field-meta.xml
<CustomField>
    <fullName>Document_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Document Template</label>
    <referenceTo>Document_Template__c</referenceTo>
    <relationshipLabel>History Trackers</relationshipLabel>
    <relationshipName>History_Trackers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/History_Tracker__c/fields/History_Tracker_Id__c.field-meta.xml
<CustomField>
    <fullName>History_Tracker_Id__c</fullName>
    <label>History_Tracker_Id</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/History_Tracker__c/fields/Object_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Object_Record_Id__c</fullName>
    <label>Object_Record_Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/History_Tracker__c/fields/Object_Record_Ids__c.field-meta.xml
<CustomField>
    <fullName>Object_Record_Ids__c</fullName>
    <label>Object Record Ids</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/History_Tracker__c/fields/Object_Record_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_Record_Name__c</fullName>
    <label>Object Record Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/History_Tracker__c/fields/Step__c.field-meta.xml
<CustomField>
    <fullName>Step__c</fullName>
    <label>Step</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/HistoryTrackerController.cls
public class HistoryTrackerController {
    //Ravi Jangid - Code here
    //For - History Tracker Records

    @AuraEnabled(cacheable=true)
    public static Map<Id, History_Tracker__c> fetchData(String recordId) {
        System.debug('recordId : '+ recordId);
        Map<Id, History_Tracker__c> mapOfHT = new Map<Id, History_Tracker__c>();
		System.debug('mapofht'+mapOfHT);
        List<History_Tracker__c> historyLst1 = [
                    SELECT Id, Document_Name__c, Document_Template__c, Status__c, Name__c, Step__c, Object_Record_Name__c, Object_Record_Id__c, History_Tracker_Id__c, Content_Version__c, Object_Name__c, Object_Record_Ids__c 
                    FROM History_Tracker__c WHERE CreatedDate = LAST_N_DAYS:365 And Document_Template__c != Null ORDER BY CreatedDate DESC LIMIT 200];    
        
        System.debug('historyLst1' +historyLst1);
        
        if (!historyLst1.isEmpty()) {
            System.debug('not empty ');
            for (History_Tracker__c history : historyLst1) {
                String objRecIds = history.Object_Record_Ids__c;
                if (objRecIds != null && objRecIds.containsIgnoreCase(recordId)) {
                    mapOfHT.put(history.id, history);
                }
            }
            System.debug('mapOfHT '+ mapOfHT);
            return mapOfHT;
        }
        return null;
    }
}