force-app/main/default/objects/Account/fields/Allocated_Credit_Limit__c.field-meta.xml
<CustomField>
    <fullName>Allocated_Credit_Limit__c</fullName>
    <label>Allocated Credit Limit</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Consumed_Credit_Limit__c.field-meta.xml
<CustomField>
    <fullName>Consumed_Credit_Limit__c</fullName>
    <label>Consumed Credit Limit</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Remaining_Credit_Limit__c.field-meta.xml
<CustomField>
    <fullName>Remaining_Credit_Limit__c</fullName>
    <label>Remaining Credit Limit</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/CreditLimitController.cls
/*
    Name : CreditLimitController
    Author :Harendra Singh
    Test Class : CreditLimitController_Test
*/
public with sharing class CreditLimitController {
    
  @AuraEnabled(cacheable=true)
    public static Account getAccounts() {
  
        User usr  = [SELECT Id, AccountId , contactId FROM user Where Id = : UserInfo.getUserId() ];
        
        Account acc = [select Id,Allocated_Credit_Limit__c, Consumed_Credit_Limit__c,Remaining_Credit_Limit__c from Account where Id = : usr.AccountId];
        return acc; 
      }
    
  }