force-app/main/default/objects/Account/fields/Allocated_Credit_Limit__c.field-meta.xml
<CustomField>
    <fullName>Allocated_Credit_Limit__c</fullName>
    <label>Allocated Credit Limit</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Application_Id__c.field-meta.xml
<CustomField>
    <fullName>Application_Id__c</fullName>
    <label>Application Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Consumed_Credit_Limit__c.field-meta.xml
<CustomField>
    <fullName>Consumed_Credit_Limit__c</fullName>
    <label>Consumed Credit Limit</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/HMC_Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>HMC_Contact_Email__c</fullName>
    <label>Contact Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/HMC_Contact_Number__c.field-meta.xml
<CustomField>
    <fullName>HMC_Contact_Number__c</fullName>
    <label>Contact Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Account/fields/Remaining_Credit_Limit__c.field-meta.xml
<CustomField>
    <fullName>Remaining_Credit_Limit__c</fullName>
    <label>Remaining Credit Limit</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Select_Region__c.field-meta.xml
<CustomField>
    <fullName>Select_Region__c</fullName>
    <label>Select Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Region_Picklist</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Distance Approval</fullName>
            </value>
            <value>
                <fullName>Document Upload</fullName>
            </value>
            <value>
                <fullName>ROI Calculation</fullName>
            </value>
            <value>
                <fullName>Advance Payment</fullName>
            </value>
            <value>
                <fullName>Approval In-Progress</fullName>
                <label>Waiting for Approval</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Onboarded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Region_Picklist.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>India</fullName>
    </customValue>
    <customValue>
        <fullName>US</fullName>
    </customValue>
    <customValue>
        <fullName>Italy</fullName>
    </customValue>
    <customValue>
        <fullName>Shri Lanka</fullName>
    </customValue>
    <customValue>
        <fullName>China</fullName>
    </customValue>
    <masterLabel>Region Picklist</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/MainClassAccount.cls
public without Sharing class  MainClassAccount {
    @AuraEnabled
    public static String createAccount(String data1) {
        
        Map<String, Object> untypedData = (Map<String, Object>) JSON.deserializeUntyped(data1);
        Account acc= new Account();
        acc.Name = (String) (String) untypedData.get('Shop Name');
        acc.Phone = (String) untypedData.get('Phone');
        acc.HMC_Contact_Number__c = (String) untypedData.get('Phone');
        acc.HMC_Contact_Email__c = (String) untypedData.get('Email');
        acc.BillingStreet = (String) untypedData.get('Billing Street');
        acc.BillingCity = (String) untypedData.get('Billing City');
        acc.BillingCountry = (String) untypedData.get('Billing Country');
        acc.BillingState = (String) untypedData.get('Billing Province'); 
        acc.BillingPostalCode = (String) untypedData.get('Billing Postal Code');
        acc.ShippingStreet = (String) untypedData.get('Shipping Street');
        acc.ShippingCity = (String) untypedData.get('Shipping City');
        acc.ShippingCountry = (String) untypedData.get('Shipping Country');
        acc.ShippingState = (String) untypedData.get('Shipping Province'); 
        acc.ShippingPostalCode = (String) untypedData.get('Shipping Postal Code');
        acc.Select_Region__c = (String) untypedData.get('Region');
        acc.Status__c = 'Document Upload';
        acc.Allocated_Credit_Limit__c=1000000.00;
        acc.Remaining_Credit_Limit__c=1000000.00;
        acc.Consumed_Credit_Limit__c=0.00;
        acc.Application_Id__c = 'APP-'+generateRandomString(12);
        if(acc!=null){
            //   try{
            User u = [SELECT Id,username FROM user WHERE username = 'anirudh.sharma@crmlanding.in.dev2' LIMIT 1];
            acc.OwnerId = u.Id;
            insert acc;
            CustomNotificationType TemplateInfoDetail = [SELECT Id, DeveloperName FROM CustomNotificationType WHERE DeveloperName='Dealer_Onboarding' LIMIT 1];
            //User u = [SELECT Id,username FROM user WHERE username = 'anirudh.sharma@crmlanding.in.dev2' LIMIT 1];
            UtilityCls.notify('Customer is created - '+acc.Name,'Customer is created - '+acc.Name,TemplateInfoDetail.Id,u.Id,acc.Id);            
            // }catch(Exception e){
            //    system.debug(e);       
            //  }
        }
        return JSON.serialize(acc);
        
    }
    
    @AuraEnabled
    public static String getAccount() {
        system.debug('in getaccount');
        Id currentUserId = UserInfo.getUserId();
        User currentUser = [SELECT Id, ContactId FROM User WHERE Id = :currentUserId LIMIT 1];
        Contact userContact = [SELECT Id, AccountId FROM Contact WHERE Id = :currentUser.ContactId LIMIT 1];
        String accid = userContact.AccountId;
        system.debug(accid);
        Account acc=[select Id,Name,Allocated_Credit_Limit__c,Consumed_Credit_Limit__c,Remaining_Credit_Limit__c from Account where id=:accid limit 1];
        return JSON.serialize(acc);
    }
    
    private static String generateRandomString(Integer length) {
        String validChars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
        String randomString = '';
        
        for (Integer i = 0; i < length; i++) {
            Integer randomIndex = Math.mod(Math.abs(Crypto.getRandomInteger()), validChars.length());
            randomString += validChars.substring(randomIndex, randomIndex + 1);
        }
        
        return randomString;
    }
    
}