force-app/main/default/objects/Account/fields/Dealer__c.field-meta.xml
<CustomField>
    <fullName>Dealer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dealer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Beat_Matrix__c/Beat_Matrix__c.object-meta.xml
<CustomObject>
    <label>Beat Matrix</label>
    <nameField>
        <displayFormat>BM-{0000}</displayFormat>
        <label>Beat Matrix Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Beat Matrix</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Beat_Matrix__c/fields/Beat_Group__c.field-meta.xml
<CustomField>
    <fullName>Beat_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Beat Group</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Beat_Matrix__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Group</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Beat_Matrix__c</referenceTo>
    <relationshipLabel>Group Member</relationshipLabel>
    <relationshipName>Beat_Matrix</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Beat_Matrix__c/fields/Dealer__c.field-meta.xml
<CustomField>
    <fullName>Dealer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dealer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Dealer</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Beat Matrix</relationshipLabel>
    <relationshipName>Beat_Matrix</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Beat_Matrix__c/recordTypes/Group_Member.recordType-meta.xml
<RecordType>
    <fullName>Group_Member</fullName>
    <active>true</active>
    <label>Group Member</label>
</RecordType>

force-app/main/default/classes/BeatMatrixGroupMembCreationCtrl.cls
public without sharing class BeatMatrixGroupMembCreationCtrl {
    @AuraEnabled(cacheable=true)
    public static beatGPMWrapper gpmemberCreation(String recordId){
        beatGPMWrapper objBeatGPMWrapper = new beatGPMWrapper();
        objBeatGPMWrapper.beatGroupMemRecordTypeId = Schema.SObjectType.Beat_Matrix__c.getRecordTypeInfosByDeveloperName().get('Group_Member').getRecordTypeId();
        if(String.isNotBlank(recordId)){
            objBeatGPMWrapper.beatGroupRecord = [Select Id,Dealer__c,Beat_Group__c from Beat_Matrix__c Where Id =: recordId];
            return objBeatGPMWrapper;
        } 
        return objBeatGPMWrapper;
    }
    @AuraEnabled
    public static void saveGroupmemberRecord(List<Beat_Matrix__c>  beatGroupMembLst){
        System.debug('beatGroupMembLst--->'+beatGroupMembLst);
        if(!beatGroupMembLst.isEmpty()){
            insert beatGroupMembLst;
        }
    }
    @AuraEnabled
    public static Account fetchDealer(String  delearId){
        if(String.isNotBlank(delearId)){
            List<Account> dealerLst = [Select Id, Name From Account Where Id =: delearId ];
            System.debug('delaerList'+dealerLst);
            return dealerLst[0] ;
        }
        return new Account();
    }

    public class beatGPMWrapper{
        @AuraEnabled
        public Beat_Matrix__c beatGroupRecord{get;set;} 
        @AuraEnabled
        public String beatGroupMemRecordTypeId{get;set;}
        
        public beatGPMWrapper(){
            beatGroupRecord = new Beat_Matrix__c();
            beatGroupMemRecordTypeId = '';
        }
    }
}