force-app/main/default/objects/Account/fields/Dealer__c.field-meta.xml
<CustomField>
    <fullName>Dealer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dealer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Dealer.recordType-meta.xml
<RecordType>
    <fullName>Dealer</fullName>
    <active>true</active>
    <label>Dealer</label>
</RecordType>

force-app/main/default/objects/Beat_Matrix__c/Beat_Matrix__c.object-meta.xml
<CustomObject>
    <label>Beat Matrix</label>
    <nameField>
        <displayFormat>BM-{0000}</displayFormat>
        <label>Beat Matrix Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Beat Matrix</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Beat_Matrix__c/fields/Beat_Group__c.field-meta.xml
<CustomField>
    <fullName>Beat_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Beat Group</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Beat_Matrix__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Group</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Beat_Matrix__c</referenceTo>
    <relationshipLabel>Group Member</relationshipLabel>
    <relationshipName>Beat_Matrix</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Beat_Matrix__c/fields/Dealer__c.field-meta.xml
<CustomField>
    <fullName>Dealer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dealer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Dealer</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Beat Matrix</relationshipLabel>
    <relationshipName>Beat_Matrix</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Beat_Matrix__c/recordTypes/Group.recordType-meta.xml
<RecordType>
    <fullName>Group</fullName>
    <active>true</active>
    <label>Group</label>
</RecordType>

force-app/main/default/classes/BeatMatrixTriggerHandler.cls
public class BeatMatrixTriggerHandler {
    public static Id groupRecordTypeId = Schema.SObjectType.Beat_Matrix__c.getRecordTypeInfosByName().get('Group').getRecordTypeId();
    public static Id groupMemberRecordTypeId = Schema.SObjectType.Beat_Matrix__c.getRecordTypeInfosByName().get('Group Member').getRecordTypeId();

    public static void beatGroup(List<Beat_Matrix__c> btLst,Map<id,Beat_Matrix__c> btgOldmap){
        Set<id> btId = new Set<id>();
        for(Beat_Matrix__c cc : btLst) {
            if(cc.Dealer__c != null || (cc.Dealer__c != null && cc.Dealer__c != btgOldmap.get(cc.Id).Dealer__c)) {
                btId.add(cc.Dealer__c); 
                System.debug('cc.Dealer__c'+cc.Dealer__c);
            }
        }
        Map<Id,Account> mapAccount = new Map<Id,Account> ([SELECT Id,(SELECT Id FROM Beat_Matrix__r WHERE RecordTypeId=:groupMemberRecordTypeId) FROM Account WHERE Id IN : btId]);
        for(Beat_Matrix__c Hmcbtg: btLst) {	
            if( Hmcbtg.Dealer__c != null && mapAccount.containsKey(Hmcbtg.Dealer__c)) {
                Account acc = mapAccount.get(Hmcbtg.Dealer__c);
                System.debug('acc.Beat_Matrix__r.size()'+acc.Beat_Matrix__r.size());
                if(acc.Beat_Matrix__r.size() > 1) {
                    Hmcbtg.addError('One dealer can not be part of multiple beat group members.'); 
                }
            }
        }
    }
}