force-app/main/default/objects/Account/fields/HMC_Dealer_Code__c.field-meta.xml
<CustomField>
    <fullName>HMC_Dealer_Code__c</fullName>
    <label>Customer Code</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Opening_Balance__c.field-meta.xml
<CustomField>
    <fullName>Opening_Balance__c</fullName>
    <label>Opening Balance</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Ledger__c/Ledger__c.object-meta.xml
<CustomObject>
    <label>Ledger</label>
    <nameField>
        <label>Ledger Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ledgers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Ledger__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Ledgers</relationshipLabel>
    <relationshipName>Ledgers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ledger__c/fields/Accumulated_Balance__c.field-meta.xml
<CustomField>
    <fullName>Accumulated_Balance__c</fullName>
    <label>Accumulated Balance</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Ledger__c/fields/Amount_in_local_Currency__c.field-meta.xml
<CustomField>
    <fullName>Amount_in_local_Currency__c</fullName>
    <label>Amount in local Currency</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Ledger__c/fields/Assignment__c.field-meta.xml
<CustomField>
    <fullName>Assignment__c</fullName>
    <label>Assignment</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ledger__c/fields/Clearing_Document__c.field-meta.xml
<CustomField>
    <fullName>Clearing_Document__c</fullName>
    <label>Clearing Document</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ledger__c/fields/Credit_Note__c.field-meta.xml
<CustomField>
    <fullName>Credit_Note__c</fullName>
    <formula>IF(
    NOT(ISBLANK( Amount_in_local_Currency__c )),
    IF(
         Amount_in_local_Currency__c  &gt;= 0,
         Amount_in_local_Currency__c ,
        null
    ),
    null
)</formula>
    <label>Credit Note</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Ledger__c/fields/Debit_Note__c.field-meta.xml
<CustomField>
    <fullName>Debit_Note__c</fullName>
    <formula>IF(
    NOT(ISBLANK( Amount_in_local_Currency__c )),
    IF(
        Amount_in_local_Currency__c &lt; 0,
        ABS(Amount_in_local_Currency__c),
        null
    ),
    null
)</formula>
    <label>Debit Note</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Ledger__c/fields/Description_Narration__c.field-meta.xml
<CustomField>
    <fullName>Description_Narration__c</fullName>
    <label>Description(Narration)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ledger__c/fields/Document_Date__c.field-meta.xml
<CustomField>
    <fullName>Document_Date__c</fullName>
    <label>Document Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Ledger__c/fields/Document_Number__c.field-meta.xml
<CustomField>
    <fullName>Document_Number__c</fullName>
    <label>Document Number</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ledger__c/fields/Invoice_Dr_Cr_Number__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Dr_Cr_Number__c</fullName>
    <label>Invoice/Dr/Cr Number)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ledger__c/fields/Local_Currency__c.field-meta.xml
<CustomField>
    <fullName>Local_Currency__c</fullName>
    <label>Local Currency</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ledger__c/fields/Posting_Date__c.field-meta.xml
<CustomField>
    <fullName>Posting_Date__c</fullName>
    <label>Posting Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Ledger__c/fields/Profit_Center__c.field-meta.xml
<CustomField>
    <fullName>Profit_Center__c</fullName>
    <label>Profit Center</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ledger__c/fields/Sales_Organisation__c.field-meta.xml
<CustomField>
    <fullName>Sales_Organisation__c</fullName>
    <label>Sales Organisation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ledger__c/fields/Special_G_L_Ind__c.field-meta.xml
<CustomField>
    <fullName>Special_G_L_Ind__c</fullName>
    <label>Special G/L Ind.</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LedgerHelperClass.cls
public class LedgerHelperClass {
    @AuraEnabled
    Public static WrapperClass  getLedgerData(Date startDate, Date endDate){//,string dmsAndSalesRepreName
        
       
        WrapperClass objWrapWire = new WrapperClass(); 
        User us = [SELECT Id, name,AccountId,Account.HMC_Dealer_Code__c	 from user Where Id =: UserInfo.getUserId()];//UserInfo.getUserId() //0051e000002xntXAAQ
        
        List<Account> accListCurrentUser = [SELECT id,Name,HMC_Dealer_Code__c	,Opening_Balance__c FROM Account WHERE Id =: us.AccountId];
        objWrapWire.currentDealerList = accListCurrentUser; 
        
        if(startDate != null && endDate != null){	
            
            List<Ledger__c> ledgerList = new List<Ledger__c>();
            
            if(startDate != null && endDate != null  ){
                system.debug('startDate>>>>>>'+startDate);
                system.debug('endDate>>>>>>'+endDate);
                ledgerList = [SELECT id,Debit_Note__c,Credit_Note__c,Sales_Organisation__c,Accumulated_Balance__c,Invoice_Dr_Cr_Number__c,Description_Narration__c,
                              Profit_Center__c,Account__c,Amount_in_local_Currency__c,Document_Number__c, Assignment__c,Clearing_Document__c, Document_Date__c,
                              Document_Type__c, Local_Currency__c,Special_G_L_Ind__c, Text__c, Posting_Date__c,Customer__c,Account__r.Name 
                              FROM Ledger__c 
                             WHERE  Posting_Date__c >= : startDate AND Posting_Date__c <=: endDate  and Account__r.Id != null
                              order by Posting_Date__c];
                system.debug('ledgerList@196=>'+ledgerList);
                
                Decimal openingBalance =accListCurrentUser[0].Opening_Balance__c;
                
                if(openingBalance != null){
                    objWrapWire.openingBalance = openingBalance;
                }
                
                if(ledgerList != null){
                    system.debug('ledgerList@215=>'+ledgerList);
                    objWrapWire.ledgerDataList = ledgerList;
                    system.debug('ledgerList@217=>'+ledgerList);
                    
                    Decimal closingBalance = 0.0;
                    system.debug('ledgerList@220=>'+ledgerList);
                    for(Ledger__c ledger: ledgerList){
                        if(ledger.Amount_in_local_Currency__c != null){
                            closingBalance = closingBalance + ledger.Amount_in_local_Currency__c;
                        }
                    }
                    //objWrapWire.openingBalance = LedgerOpeningBalance.currentUserOpeningBalance();
                    objWrapWire.closingBalance = closingBalance;
                }
            }
        }
        
        return objWrapWire;
    }
    @AuraEnabled
    Public static WrapperClass getLedgerFilterData(Date startDate, Date endDate,String accDealerId,String customerIsAll,String salesOrganisation){//String salesRepresentativeSelectDealer
        
        WrapperClass objWrapWire = new WrapperClass(); 
        User us = [SELECT Id, name,AccountId,Account.HMC_Dealer_Code__c	 from user Where Id =: UserInfo.getUserId()];//UserInfo.getUserId() //0051e000002xntXAAQ
        
        List<Account> accListCurrentUser = [SELECT id,Name,HMC_Dealer_Code__c	,Opening_Balance__c FROM Account WHERE Id =: us.AccountId];
        objWrapWire.currentDealerList = accListCurrentUser; 
        
        if(startDate != null && endDate != null){	
            
            List<Ledger__c> ledgerList = new List<Ledger__c>();
            
            if(startDate != null && endDate != null  ){
                system.debug('startDate>>>>>>'+startDate);
                system.debug('endDate>>>>>>'+endDate);
                system.debug('salesOrganisation@@177'+salesOrganisation);
                ledgerList = [SELECT id,Debit_Note__c,Credit_Note__c,Sales_Organisation__c,Accumulated_Balance__c,Invoice_Dr_Cr_Number__c,Description_Narration__c,
                              Profit_Center__c,Account__c,Amount_in_local_Currency__c,Document_Number__c, Assignment__c,Clearing_Document__c, Document_Date__c,
                              Document_Type__c, Local_Currency__c,Special_G_L_Ind__c, Text__c, Posting_Date__c,Customer__c,Account__r.Name 
                              FROM Ledger__c 
                             WHERE  Posting_Date__c >= : startDate AND Posting_Date__c <=: endDate  and Account__r.Id != null
                              order by Posting_Date__c];
                system.debug('ledgerList@196=>'+ledgerList);
                
                Decimal openingBalance =accListCurrentUser[0].Opening_Balance__c;
                
                if(openingBalance != null){
                    objWrapWire.openingBalance = openingBalance;
                }
                
                if(ledgerList != null){
                    system.debug('ledgerList@215=>'+ledgerList);
                    objWrapWire.ledgerDataList = ledgerList;
                    system.debug('ledgerList@217=>'+ledgerList);
                    
                    Decimal closingBalance = 0.0;
                    system.debug('ledgerList@220=>'+ledgerList);
                    for(Ledger__c ledger: ledgerList){
                        if(ledger.Amount_in_local_Currency__c != null){
                            closingBalance = closingBalance + ledger.Amount_in_local_Currency__c;
                        }
                    }
                    //objWrapWire.openingBalance = LedgerOpeningBalance.currentUserOpeningBalance();
                    objWrapWire.closingBalance = closingBalance;
                }
            }
        }
        
        return objWrapWire;
    }
    public class WrapperClass {
        
        @AuraEnabled
        public List<Ledger__c> ledgerDataList;
        @AuraEnabled
        public List<Account> accDealerList;
        @AuraEnabled
        public Decimal openingBalance;
        @AuraEnabled
        public Decimal closingBalance;
        @AuraEnabled
        public List<Account> accSubDealerList;
        @AuraEnabled
        public List<String> accumulatedList;
        @AuraEnabled
        public List<Account> currentDealerList;
        
    }
}