force-app/main/default/objects/Account/fields/HMC_Dealer_Code__c.field-meta.xml
<CustomField>
    <fullName>HMC_Dealer_Code__c</fullName>
    <label>Customer Code</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Path_Status__c.field-meta.xml
<CustomField>
    <fullName>Path_Status__c</fullName>
    <defaultValue>&quot;Unqualified&quot;</defaultValue>
    <label>Path Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unqualified</fullName>
                <default>true</default>
                <label>Unqualified</label>
            </value>
            <value>
                <fullName>Qualified</fullName>
            </value>
            <value>
                <fullName>Dealer Onboarded</fullName>
                <label>Customer Onboarded</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Distance Approval</fullName>
            </value>
            <value>
                <fullName>Document Upload</fullName>
            </value>
            <value>
                <fullName>ROI Calculation</fullName>
            </value>
            <value>
                <fullName>Advance Payment</fullName>
            </value>
            <value>
                <fullName>Approval In-Progress</fullName>
                <label>Waiting for Approval</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Onboarded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Dealer.recordType-meta.xml
<RecordType>
    <fullName>Dealer</fullName>
    <active>true</active>
    <label>Dealer</label>
</RecordType>

force-app/main/default/classes/AccountTriggerHandler2.cls
public class AccountTriggerHandler2 {
    public static Boolean isRun = true;
    public static void beforeUpdateAccount(List<Account> newList, Map<Id, Account> oldMap) {
        isRun = false;
        Set<Id> accIdSet = new Set<Id>();
        Map<Id, User> userMap = new Map<Id, User>();
        List<Account> updateAccountList = new List<Account>();
        for (Account item : newList) {
            if ((item.Path_Status__c != oldMap.get(item.Id).Path_Status__c) && (oldMap.get(item.Id).Path_Status__c == 'Qualified' && item.Path_Status__c == 'Dealer Onboarded') && item.HMC_Dealer_Code__c != NULL) {
                Account accObj = new Account();
                accObj.Id = item.Id;
                accObj.Status__c = 'Onboarded';
                updateAccountList.add(accObj);
            }
        }
        if(updateAccountList!=null){
            update updateAccountList;
        }
    }
}