force-app/main/default/objects/custome_Profile__c/custome_Profile__c.object-meta.xml
<CustomObject>
    <label>customeProfile</label>
    <nameField>
        <label>Custome Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>customeProfiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/custome_Profile__c/fields/Permission_Name__c.field-meta.xml
<CustomField>
    <fullName>Permission_Name__c</fullName>
    <label>Permission Name</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/ProfileController.cls
public class ProfileController {
    
    @AuraEnabled(cacheable=true)
    public static List<Profile> getAllProfiles() {
        return [SELECT Id, Name FROM Profile];
    }
   /* @AuraEnabled
    public static void saveProfilesData(String profilesData) {
        System.debug('helo profile');
        custome_Profile__c proData = new custome_Profile__c();
        proData.Permission_Name__c=profilesData;
        
        insert proData;
        System.debug('submited are : '+proData);
    }*/

}