force-app/main/default/objects/Price_List__c/Price_List__c.object-meta.xml
<CustomObject>
    <label>Price List</label>
    <nameField>
        <label>Price List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Price Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Price_List__c/fields/Content_Link__c.field-meta.xml
<CustomField>
    <fullName>Content_Link__c</fullName>
    <label>Content Link</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Price_List__c/fields/Sales_Office__c.field-meta.xml
<CustomField>
    <fullName>Sales_Office__c</fullName>
    <label>Sales Office</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Sales_Office__c.field-meta.xml
<CustomField>
    <fullName>Sales_Office__c</fullName>
    <label>Sales Office</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PriceListCtrl.cls
public with sharing class PriceListCtrl {
    @AuraEnabled
    public static String getPriceList(){
        try{
            String pdfUrl = '';
            String currentUserId = UserInfo.getUserId();
            String currentUserSalesOffice = [select id,Sales_Office__c from user where id = :currentUserId Limit 1].Sales_Office__c;
            if(!String.isBlank(currentUserSalesOffice)){
                Price_List__c pl = [select id,name,Content_Link__c from Price_List__c where Name = :currentUserSalesOffice order by CreatedDate desc limit 1];
                pdfUrl = pl.Content_Link__c;
                return pdfUrl;
            }
            return pdfUrl;
        }Catch(Exception e){
            return '';
        }
    }
    
   
    @AuraEnabled
    public static String getSalesOffice(){
        String currentUserId = UserInfo.getUserId();
        System.debug('currentUserId: '+currentUserId);
        String currentUserSalesOffice = [select id,Sales_Office__c from user where id = :currentUserId Limit 1].Sales_Office__c;
        return currentUserSalesOffice;
    }
    
    @AuraEnabled
    public static String getRollingSalesOffice(){
        String currentUserId = UserInfo.getUserId();
        String currentUserSalesOffice = [select id,Sales_Office__c from user where id = :currentUserId Limit 1].Sales_Office__c;
        String showDate = String.valueOf(System.today()).split(' ')[0];
        if(currentUserSalesOffice != '' || currentUserSalesOffice != NULL){
            return currentUserSalesOffice+'-'+showDate;
        }else{
            return '';
        }
    }
    @AuraEnabled(cacheable=true)
    public static List<Price_List__c> getPriceListName() {
       
        User currentUser = [SELECT id,Sales_Office__c FROM User WHERE Id =: UserInfo.getUserId()];
        List<Price_List__c> priceList = [SELECT  id,Name,Sales_Office__c,Content_Link__c FROM Price_List__c
                                         WHERE Sales_Office__c =: currentUser.Sales_Office__c AND Active__c = true] ;
        return priceList;
    }
     @AuraEnabled(cacheable=true)
    public static Price_List__c getAttachmentUrl(String selectedAttachmentId) {
        system.debug('selectedAttachmentId==>'+selectedAttachmentId);
        Price_List__c priceList = [SELECT  id,Name,Sales_Office__c,Content_Link__c FROM Price_List__c WHERE Id =:selectedAttachmentId ] ;
        
            return priceList;
    }
}