force-app/main/default/objects/Voucher__c/Voucher__c.object-meta.xml
<CustomObject>
    <label>Voucher</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Voucher Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vouchers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Voucher__c/fields/Gu_Id__c.field-meta.xml
<CustomField>
    <fullName>Gu_Id__c</fullName>
    <externalId>true</externalId>
    <label>GuId</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Voucher__c/fields/PartyName__c.field-meta.xml
<CustomField>
    <fullName>PartyName__c</fullName>
    <label>PartyName</label>
    <length>180</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Voucher__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Excel</fullName>
            </value>
            <value>
                <fullName>Tally</fullName>
            </value>
            <value>
                <fullName>ERP</fullName>
            </value>
            <value>
                <fullName>Other CRM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Voucher__c/fields/TypeName__c.field-meta.xml
<CustomField>
    <fullName>TypeName__c</fullName>
    <label>TypeName</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Voucher__c/fields/Voucher_Data__c.field-meta.xml
<CustomField>
    <fullName>Voucher_Data__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Voucher Data</label>
    <referenceTo>Voucher_Data__c</referenceTo>
    <relationshipLabel>Vouchers</relationshipLabel>
    <relationshipName>Vouchers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Voucher__c/fields/VoucherNumber__c.field-meta.xml
<CustomField>
    <fullName>VoucherNumber__c</fullName>
    <label>VoucherNumber</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Voucher__c/fields/VoucherType__c.field-meta.xml
<CustomField>
    <fullName>VoucherType__c</fullName>
    <label>VoucherType</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Voucher_Data__c/Voucher_Data__c.object-meta.xml
<CustomObject>
    <label>Voucher Data</label>
    <nameField>
        <displayFormat>VD-{0000}</displayFormat>
        <label>Voucher Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Voucher Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Voucher_Data__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Voucher Data</relationshipLabel>
    <relationshipName>Voucher_Datas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TallyGuest.cls
@RestResource(urlMapping='/createAccounts/*')
global  class TallyGuest {
    
    @HttpPost
    global static String createAccounts() {
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        List<Voucher__c> vchListnew = [Select id,Gu_Id__c from Voucher__c];
        
        Map<String,String> vchMap = new Map<String,String>();
        system.debug('vchMap'+vchMap);
        for (Voucher__c vchObj : vchListnew){
            system.debug('vchObj.Gu_Id__c'+vchObj.Gu_Id__c);
            if(vchObj.Gu_Id__c != null){
                vchMap.put(vchObj.Gu_Id__c,vchObj.Id);
            }
        }
        try { 
            Map<String, Object> requestData = (Map<String, Object>) JSON.deserializeUntyped(req.requestBody.toString());
            system.debug('requestData'+requestData);
            if (requestData.containsKey('VCHS')) {
                Map<String, Object> ledgersData = (Map<String, Object>) requestData.get('VCHS');
                if (ledgersData.containsKey('VCH')) {
                    List<Object> ledgerList = (List<Object>) ledgersData.get('VCH');
                    List<Voucher__c> vchListUpdate = new List<Voucher__c>();
                    List<Voucher__c> vchListInsert = new List<Voucher__c>();
                    Set<String> strList = new Set<String>();
                    
                    if (!ledgerList.isEmpty()) {
                        for (Object ledgerItem : ledgerList) {
                            Map<String, Object> item = (Map<String, Object>) ledgerItem;
                            Integer VchNumber = Integer.valueof(item.get('VoucherNumber'));
                            String VchType = String.valueOf(item.get('VoucherType'));
                            String partyName = String.valueOf(item.get('PartyName'));
                            String TypeName = String.valueOf(item.get('TypeName'));
                            Double Amount = Double.valueof(item.get('Amount'));
                            Integer Quantity = Integer.valueof(item.get('Quantity'));
                            String GuId = String.valueOf(item.get('Guid'));
                            String CompanyName = String.valueOf(item.get('CompanyName'));
                            strList.add(CompanyName);
                            //Date dates = Date.valueof(item.get('Date'));
                            if(vchMap.containsKey(GuId)){
                                system.debug('Inside'+vchMap.get(GuId));
                                Voucher__c vch = new Voucher__c();
                                vch.Id = vchMap.get(GuId);
                                vch.VoucherNumber__c = VchNumber;
                                vch.PartyName__c = partyName;
                                vch.VoucherType__c = VchType;
                                vch.TypeName__c =TypeName;
                                vch.Amount__c = Amount;
                                vch.Quantity__c = Quantity;
                                vch.Source__c = 'Excel';
                                vch.Company_Name__c = CompanyName;
                                // Vch.Date__c = dates;
                                vchListUpdate.add(vch);
                            }else if(!vchMap.containsKey(GuId)) {
                                system.debug('Inside Insert');
                                Voucher__c vchinsert = new Voucher__c();
                                vchinsert.VoucherNumber__c = VchNumber;
                                vchinsert.PartyName__c = partyName;
                                vchinsert.VoucherType__c = VchType;
                                vchinsert.TypeName__c =TypeName;
                                vchinsert.Amount__c = Amount;
                                vchinsert.Quantity__c = Quantity;
                                vchinsert.Gu_Id__c = GuId;
                                vchinsert.Source__c = 'Tally';
                                vchinsert.Company_Name__c = CompanyName;
                                // Vch.Date__c = dates;
                                vchListInsert.add(vchinsert);
                            }
                        }
                        List<Account> accList = [Select id from Account where Name =:strList];
                        Voucher_Data__c vchObj = new Voucher_Data__c();
                        vchObj.Account__c = accList[0].id ;
                        vchObj.Source__c = 'Tally';
                        insert vchObj;
                        if (!vchListUpdate.isEmpty()) {
                            for(Voucher__c vcObj: vchListUpdate){vcObj.Voucher_Data__c = vchObj.id ;}
                            Update vchListUpdate;
                        }
                        if(!vchListInsert.isEmpty()){
                            for(Voucher__c vcObj: vchListInsert){vcObj.Voucher_Data__c = vchObj.id ;}
                            insert vchListInsert;
                        }
                    }
                }
            }
            return 'Accounts created successfully.';
        } catch (Exception e) {
            res.statusCode = 400; // Bad Request
            return 'Error: ' + e.getMessage();
        }
    }
}