force-app/main/default/objects/Document_Store__c/Document_Store__c.object-meta.xml
<CustomObject>
    <label>Document Store</label>
    <nameField>
        <displayFormat>DS-{0000}</displayFormat>
        <label>Document Store Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Document Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Document_Store__c/fields/FooterHTML__c.field-meta.xml
<CustomField>
    <fullName>FooterHTML__c</fullName>
    <label>FooterHTML</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/classes/TestDocController.cls
@isTest
private class TestDocController {
    
    @isTest
    static void testSetValues() {
        DocController controller = new DocController();
        
        Document_Store__c mockDocument = new Document_Store__c(FooterHTML__c = 'Mock Footer HTML');
        Attachment mockAttachment = new Attachment(Body = Blob.valueOf('Mock Body Content'));
      //  ContentDocumentLink mockContentDocumentLink = new ContentDocumentLink(ContentDocumentId = 'mockContentDocumentId', LinkedEntityId = 'someRecordId');
        
        controller.setValues();
        
    }   
}