force-app/main/default/objects/Document_Store__c/Document_Store__c.object-meta.xml
<CustomObject>
    <label>Document Store</label>
    <nameField>
        <displayFormat>DS-{0000}</displayFormat>
        <label>Document Store Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Document Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Document_Store__c/fields/FooterHTML__c.field-meta.xml
<CustomField>
    <fullName>FooterHTML__c</fullName>
    <label>FooterHTML</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/classes/DocController.cls
public class DocController {
    //public String header{get;set;}
    public String body{get;set;}
    public String footer{get;set;}
    public String contentVersionId{get;set;}
    public Integer currentPage { get; set; }
    
    public void setValues(){
        String recordId = apexPages.currentPage().getParameters().get('recordId');
        
        System.debug('reocrd id of doc controller '+recordId);
        Document_Store__c obj = [SELECT Id, FooterHTML__c FROM Document_Store__c WHERE Id =: recordId LIMIT 1]; 
        footer = obj.FooterHTML__c;
        Attachment att = [ SELECT  Body FROM Attachment WHERE ParentId =: recordId Limit 1];
        System.debug('--- att '+ att.Body);
        body =  att.Body.toString();
        contentVersionId = [SELECT ContentDocument.LatestPublishedVersionId FROM ContentDocumentLink WHERE LinkedEntityId =: recordId]?.ContentDocument.LatestPublishedVersionId;
    }
}