force-app/main/default/objects/HMC_Target__c/HMC_Target__c.object-meta.xml
<CustomObject>
    <label>Dealer Target</label>
    <nameField>
        <displayFormat>T-{00000}</displayFormat>
        <label>Target Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Targets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HMC_Target__c/fields/HMC_Achievement_Amount__c.field-meta.xml
<CustomField>
    <fullName>HMC_Achievement_Amount__c</fullName>
    <label>Achievement Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HMC_Target__c/fields/HMC_Dealer__c.field-meta.xml
<CustomField>
    <fullName>HMC_Dealer__c</fullName>
    <label>Dealer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Targets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/HMC_Target__c/fields/HMC_Month__c.field-meta.xml
<CustomField>
    <fullName>HMC_Month__c</fullName>
    <label>Month</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>January</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>February</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>March</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>April</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>May</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>June</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>July</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>August</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>September</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>October</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>November</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>December</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HMC_Target__c/fields/HMC_Year__c.field-meta.xml
<CustomField>
    <fullName>HMC_Year__c</fullName>
    <label>Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2022</fullName>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2025</fullName>
            </value>
            <value>
                <fullName>2026</fullName>
            </value>
            <value>
                <fullName>2027</fullName>
            </value>
            <value>
                <fullName>2028</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/HMC_Invoice_Amount__c.field-meta.xml
<CustomField>
    <fullName>HMC_Invoice_Amount__c</fullName>
    <label>Invoice Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/HMC_Invoice_Date__c.field-meta.xml
<CustomField>
    <fullName>HMC_Invoice_Date__c</fullName>
    <label>Invoice Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/HMC_Order_Number__c.field-meta.xml
<CustomField>
    <fullName>HMC_Order_Number__c</fullName>
    <label>ERP Order number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipName>OrderLineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/OrderPaymentHandler.cls
public class OrderPaymentHandler {
public static void afterUpdateTarget(List<Order__c> newoppotunity,Map<Id,Order__c> oldMap){
        Set<Id> accIds= new Set<Id>();
        for(Order__c opp: newoppotunity){
            if(opp !=null &&  opp.HMC_Invoice_Amount__c != oldMap.get(opp.id).HMC_Invoice_Amount__c){
                system.debug('opp'+opp);
                accIds.add(opp.Account__c);
            }
        }
        
        Map<map<String,String>,List<Order__c>> oppMap=new  Map<map<String,String>,List<Order__c>>();
        if(accIds !=null){
            for(Order__c opp:[SELECT Id,HMC_Invoice_Date__c,CreatedDate,HMC_Invoice_Amount__c FROM Order__c WHERE HMC_Order_Number__c != null AND Account__c IN :accIds]){
                system.debug('opp'+opp);
                if(opp.CreatedDate != null){
                map<String,String> monthYearMap=new  map<String,String>();
                String month=String.valueOf(opp.CreatedDate.month());
                String year = String.valueOf(opp.CreatedDate.year());
                system.debug('month'+month);
                system.debug('year'+year);
                monthYearMap.put(month, year);
                List<Order__c> oppList = oppMap.get(monthYearMap);
                if(oppList == null)
                    oppList = new List<Order__c>();
                oppList.add(opp);
                system.debug('monthYearMap'+monthYearMap);
                system.debug('oppList'+oppList);
                oppMap.put(monthYearMap,oppList);
                }
            }
        }
        system.debug('oppMap'+oppMap);
        List<HMC_Target__c> targateList=new  List<HMC_Target__c>();
        if(accIds !=null){
            for(HMC_Target__c HMCTarget:[SELECT Id,HMC_Month__c,HMC_Year__c,HMC_Achievement_Amount__c FROM HMC_Target__c WHERE HMC_Dealer__c IN :accIds ]){
                system.debug('HMCTarget'+HMCTarget);
                if(HMCTarget.HMC_Year__c != null && HMCTarget.HMC_Month__c != null){
                    Integer achiveMentAmount=0;
                    system.debug('HMCTarget'+HMCTarget);
                    map<String,String> yearMonthMap=new map<String,String>();
                    yearMonthMap.put(HMCTarget.HMC_Month__c,HMCTarget.HMC_Year__c);
                    if(oppMap.containsKey(yearMonthMap)){
                        for(Order__c opp: oppMap.get(yearMonthMap)){
                            if(opp.HMC_Invoice_Amount__c != null){
                                achiveMentAmount=achiveMentAmount+integer.valueOf(opp.HMC_Invoice_Amount__c); 
                            }
                        }
                    }
                    system.debug('achiveMentAmount'+achiveMentAmount);
                    HMCTarget.HMC_Achievement_Amount__c=achiveMentAmount;
                    targateList.add(HMCTarget);
                }
                
            }
        }
        system.debug('targateList'+targateList);
        if(!targateList.isEmpty()){
            system.debug('targateList'+targateList);
            update targateList;
            
        }
    }
}