force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipName>OrderLineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Scheme__c.field-meta.xml
<CustomField>
    <fullName>Scheme__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Scheme</label>
    <referenceTo>Scheme__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/recordTypes/Order.recordType-meta.xml
<RecordType>
    <fullName>Order</fullName>
    <active>true</active>
    <label>Order</label>
</RecordType>

force-app/main/default/objects/Scheme__c/Scheme__c.object-meta.xml
<CustomObject>
    <label>Scheme</label>
    <nameField>
        <label>Scheme Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schemes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/OrderController.cls
public class OrderController {
    @AuraEnabled
    public static Id createOrder(String accountId,String schemeId) {
        String orderRecordType = Schema.getGlobalDescribe().get('Order__c').getDescribe().getRecordTypeInfosByName().get('Order').getRecordTypeId();
        Order__c newOrder = new Order__c();
        newOrder.RecordTypeId = orderRecordType;
        newOrder.Account__c = accountId;
        newOrder.Scheme__c = schemeId;
        insert newOrder;
        return newOrder.Id;
    }
    
    @AuraEnabled(cacheable=true)
    public static Account getContactAccountName() {
        user u = [SELECT Id,Contact.AccountId FROM user where id=:UserInfo.getUserId()];
        Account acc=[SELECT Id,Name,BillingStreet, 
                     BillingCity, 
                     BillingState, 
                     BillingPostalCode, 
                     BillingCountry, 
                     ShippingStreet, 
                     ShippingCity, 
                     ShippingState, 
                     ShippingPostalCode, 
                     ShippingCountry from Account where id =:u.Contact.AccountId];
        return acc;
    }
    
}