force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipName>OrderLineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Route_Plan__c.field-meta.xml
<CustomField>
    <fullName>Route_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Route Plan</label>
    <referenceTo>Route_Plan__c</referenceTo>
    <relationshipLabel>Expenses</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/recordTypes/Expense.recordType-meta.xml
<RecordType>
    <fullName>Expense</fullName>
    <active>true</active>
    <label>Expense</label>
</RecordType>

force-app/main/default/objects/Route_Plan__c/Route_Plan__c.object-meta.xml
<CustomObject>
    <label>Route Plan</label>
    <nameField>
        <label>Route Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Route Plan</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Route_Plan__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Update Needed</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Route_Plan__c/fields/ASM__c.field-meta.xml
<CustomField>
    <fullName>ASM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ASM</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Route_Plan</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Route_Plan__c/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <label>Month</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
                <label>January</label>
            </value>
            <value>
                <fullName>02</fullName>
                <label>February</label>
            </value>
            <value>
                <fullName>03</fullName>
                <label>March</label>
            </value>
            <value>
                <fullName>04</fullName>
                <label>April</label>
            </value>
            <value>
                <fullName>05</fullName>
                <label>May</label>
            </value>
            <value>
                <fullName>06</fullName>
                <label>June</label>
            </value>
            <value>
                <fullName>07</fullName>
                <label>July</label>
            </value>
            <value>
                <fullName>08</fullName>
                <label>August</label>
            </value>
            <value>
                <fullName>09</fullName>
                <label>September</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>October</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>November</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>December</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Route_Plan__c/fields/Route_Plan__c.field-meta.xml
<CustomField>
    <fullName>Route_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Route Plan</label>
    <referenceTo>Route_Plan__c</referenceTo>
    <relationshipLabel>Route Plan Activity</relationshipLabel>
    <relationshipName>Route_Plan</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Route_Plan__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2025</fullName>
            </value>
            <value>
                <fullName>2026</fullName>
            </value>
            <value>
                <fullName>2027</fullName>
            </value>
            <value>
                <fullName>2028</fullName>
            </value>
            <value>
                <fullName>2029</fullName>
            </value>
            <value>
                <fullName>2030</fullName>
            </value>
            <value>
                <fullName>2031</fullName>
            </value>
            <value>
                <fullName>2032</fullName>
            </value>
            <value>
                <fullName>2033</fullName>
            </value>
            <value>
                <fullName>2034</fullName>
            </value>
            <value>
                <fullName>2035</fullName>
            </value>
            <value>
                <fullName>2036</fullName>
            </value>
            <value>
                <fullName>2037</fullName>
            </value>
            <value>
                <fullName>2038</fullName>
            </value>
            <value>
                <fullName>2039</fullName>
            </value>
            <value>
                <fullName>2040</fullName>
            </value>
            <value>
                <fullName>2041</fullName>
            </value>
            <value>
                <fullName>2042</fullName>
            </value>
            <value>
                <fullName>2043</fullName>
            </value>
            <value>
                <fullName>2044</fullName>
            </value>
            <value>
                <fullName>2045</fullName>
            </value>
            <value>
                <fullName>2046</fullName>
            </value>
            <value>
                <fullName>2047</fullName>
            </value>
            <value>
                <fullName>2048</fullName>
            </value>
            <value>
                <fullName>2049</fullName>
            </value>
            <value>
                <fullName>2050</fullName>
            </value>
            <value>
                <fullName>2051</fullName>
            </value>
            <value>
                <fullName>2052</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Route_Plan__c/recordTypes/Activity.recordType-meta.xml
<RecordType>
    <fullName>Activity</fullName>
    <active>true</active>
    <label>Activity</label>
</RecordType>

force-app/main/default/objects/Route_Plan__c/recordTypes/Month.recordType-meta.xml
<RecordType>
    <fullName>Month</fullName>
    <active>true</active>
    <label>Month</label>
</RecordType>

force-app/main/default/classes/RoutePlanTriggerHandler.cls
public class RoutePlanTriggerHandler {
    
    
    //this method work on before opreations
    public static void beforeOpreations(List<Route_Plan__c> newRoutePlanLst){
        Id activityRecordTypeId = Schema.SObjectType.Route_Plan__c.getRecordTypeInfosByName().get('Activity').getRecordTypeId();
        Id monthRecordTypeId = Schema.SObjectType.Route_Plan__c.getRecordTypeInfosByName().get('Month').getRecordTypeId();
        Set<Id> hmcRoutePlanIDs=new Set<Id>();
        Id profileId= userinfo.getProfileId();
        String profileName=[Select Id,Name from Profile where Id=:profileId].Name;
        system.debug('ProfileName'+profileName);      
        List<Route_Plan__c> hmcRoutePlanList=new List<Route_Plan__c>();
        if(!hmcRoutePlanIDs.isEmpty() || hmcRoutePlanIDs!=null ){
            System.debug(hmcRoutePlanIDs);
            hmcRoutePlanList=[SELECT Id,Approval_Status__c,Month__c,Year__c,ASM__c FROM Route_Plan__c
                              Where Id NOT In : hmcRoutePlanIDs AND RecordTypeId=:monthRecordTypeId];         
        }else{
            hmcRoutePlanList=[SELECT Id,Approval_Status__c,Month__c,Year__c,ASM__c FROM Route_Plan__c WHERE RecordTypeId=:monthRecordTypeId ];
        }
        System.debug('hmcRoutePlanList'+hmcRoutePlanList);
        if(!hmcRoutePlanList.isEmpty()){
            System.debug(hmcRoutePlanList);
            Set<String> routePlandeatils=new Set<String>();
            for(Route_Plan__c hmcObj:hmcRoutePlanList){
                String rouDetails='';
                if(String.isNotBlank(hmcObj.ASM__c) && (hmcObj.Approval_Status__c=='Rejected' || hmcObj.Approval_Status__c=='Draft')){
                    System.debug(hmcObj.Month__c);
                    rouDetails=hmcObj.ASM__c + String.valueOf(hmcObj.Month__c) + hmcObj.Year__c;
                    routePlandeatils.add(rouDetails);
                    System.debug(routePlandeatils);
                }
            }
        }
    }
    
    //this method work on after opreations
    public static void afterUpdate(List<Route_Plan__c> newRoutePlanLst, Map<Id,Route_Plan__c> oldRoutePlanMap){
        Id activityRecordTypeId = Schema.SObjectType.Route_Plan__c.getRecordTypeInfosByName().get('Activity').getRecordTypeId();
        Id monthRecordTypeId = Schema.SObjectType.Route_Plan__c.getRecordTypeInfosByName().get('Month').getRecordTypeId();
        Id expenseRecordTypeId = Schema.SObjectType.Order__c.getRecordTypeInfosByName().get('Expense').getRecordTypeId();
        
        Set<Id> ids = new  Set<Id>();
        List<Order__c> routExpDet = new List<Order__c>();
        for(Route_Plan__c routPlan : newRoutePlanLst){
            ids.add(routPlan.id);  
        }
        
        Set<Date> datSet = new Set<Date>();
        system.debug('ids'+ids);
        List<Route_Plan__c> roughtPlanActivLst1 = [SELECT Id,Visit_Date__c,Route_Plan__c FROM Route_Plan__c WHERE RecordTypeId=:activityRecordTypeId AND Route_Plan__c =: ids];
        system.debug('roughtPlanActivLst1'+roughtPlanActivLst1);
        if(!roughtPlanActivLst1.isEmpty()){
            for(Route_Plan__c obj : roughtPlanActivLst1 ){
                datSet.add(obj.Visit_Date__c); 
            }
        }
        List<date> dLst = new List<date>();
        for(date d : datSet){
            dLst.add(d);
        }
        
        //system.debug('ans 1 ==>'+datSet);
        
        List< Route_Plan__c> roughtPlanActivLst = [SELECT Id,Visit_Date__c,Route_Plan__c FROM Route_Plan__c WHERE Route_Plan__c =: ids AND Visit_Date__c in: datSet AND RecordTypeId=:activityRecordTypeId];
        system.debug('ans==>'+roughtPlanActivLst);
        for(Route_Plan__c objj : newRoutePlanLst){
            if(objj.Approval_Status__c == 'Approved' && !dLst.isEmpty() && oldRoutePlanMap.get(objj.id).Approval_Status__c != objj.Approval_Status__c ){
                for(integer i=0; i<dLst.size(); i++){
                    
                    Order__c expDetails = new Order__c();
                    expDetails.RecordTypeId= expenseRecordTypeId;
                    expDetails.Route_Plan__c =   roughtPlanActivLst[i].Route_Plan__c;                 //ids[i];
                    expDetails.Visit_Date__c = dLst[i];
                    routExpDet.add(expDetails);          
                }   
            }
        }
        if(!routExpDet.isEmpty()){
           // insert routExpDet;
        }
    }
    
    
    public static void deleteRelatedRecords(List<Route_Plan__c> newRoutePlanLst){
    Id activityRecordTypeId = Schema.SObjectType.Route_Plan__c.getRecordTypeInfosByName().get('Activity').getRecordTypeId();
    Id monthRecordTypeId = Schema.SObjectType.Route_Plan__c.getRecordTypeInfosByName().get('Month').getRecordTypeId();
    Id expenseRecordTypeId = Schema.SObjectType.Order__c.getRecordTypeInfosByName().get('Expense').getRecordTypeId();
    
        Set<Id> deletedIdSet = new Set<Id>();
        for(Route_Plan__c deletedPlans :newRoutePlanLst){
            system.debug('deletedPlans.RecordTypeId=====>'+deletedPlans.RecordTypeId);
             system.debug('monthRecordTypeId============>'+monthRecordTypeId);
            if(deletedPlans.RecordTypeId==monthRecordTypeId){
                deletedIdSet.add(deletedPlans.Id);
            }
        }
        
        if(deletedIdSet.size()>0){
           List<Route_Plan__c> activityToBeDeleted = [SELECT Id,Route_Plan__c FROM Route_Plan__c WHERE 
                                                      RecordTypeId=:activityRecordTypeId AND 
                                                      Route_Plan__c IN:deletedIdSet];
            system.debug('activityToBeDeleted====>'+activityToBeDeleted.size());
            if(activityToBeDeleted.size()>0){
                delete activityToBeDeleted;
            }
            
            List<Order__c> expenseToBeDeleated = [SELECT Id,Route_Plan__c FROM Order__c WHERE
                                                  RecordTypeId=:expenseRecordTypeId AND
                                                  Route_Plan__c IN:deletedIdSet];
            system.debug('expenseToBeDeleated====>'+expenseToBeDeleated.size());
            if(expenseToBeDeleated.size()>0){
                delete expenseToBeDeleated;
            }
        }
    }
}