force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/HMC_Invoice_Amount__c.field-meta.xml
<CustomField>
    <fullName>HMC_Invoice_Amount__c</fullName>
    <label>Invoice Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipName>OrderLineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>product2__c</referenceTo>
    <relationshipName>OrderLineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/ProductCode__c.field-meta.xml
<CustomField>
    <fullName>ProductCode__c</fullName>
    <label>Standard Product Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/UnitPrice__c.field-meta.xml
<CustomField>
    <fullName>UnitPrice__c</fullName>
    <label>Sales Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order__c/recordTypes/Order.recordType-meta.xml
<RecordType>
    <fullName>Order</fullName>
    <active>true</active>
    <label>Order</label>
</RecordType>

force-app/main/default/objects/product2__c/product2__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/product2__c/fields/BusinessUnitType__c.field-meta.xml
<CustomField>
    <fullName>BusinessUnitType__c</fullName>
    <label>Business Unit Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hero</fullName>
            </value>
            <value>
                <fullName>Firefox</fullName>
            </value>
            <value>
                <fullName>Lectro</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/InvoiceOrderReceiptCls.cls
public class InvoiceOrderReceiptCls {
    public Id orderId{get; set;}
    public Static String orderDate{get; set;}
    public Static Order__c orderData {get; set;}
    public Static List<Order__c> orderItemLst {get; set;}
    
    public InvoiceOrderReceiptCls(){
        orderDate = String.valueOf(System.today());
        String queryString ='';
        orderId = ApexPages.currentPage().getParameters().get('id');
        orderData = getOrderData(orderId);
        System.debug('orderData: '+orderData);
        orderItemLst = getOrderItems(orderId);
        System.debug('orderItemLst: '+orderItemLst);
    }
    
    public static Order__c getOrderData(Id orderId){
        try{
            String orderRecordType = Schema.getGlobalDescribe().get('Order__c').getDescribe().getRecordTypeInfosByName().get('Order').getRecordTypeId();
            Order__c order = [SELECT Id,Account__r.HMC_Contact_Number__c,Account__r.HMC_Contact_Email__c,HMC_Invoice_Amount__c,Account__r.ShippingStreet, Account__r.ShippingState,Account__r.ShippingCountry,Account__r.ShippingCity,  Account__r.BillingStreet,  Account__r.BillingState, Account__r.BillingCountry, Account__r.BillingCity,createdDate FROM Order__c WHERE Id =: orderId AND RecordTypeId = :orderRecordType LIMIT 1];
            if(order != null){
                orderDate = String.valueOf(order.createdDate).split(' ')[0];
                //updateOrder(orderId);
                return order;
            }
            return null;
        }Catch(Exception e){
            return null;
        }
    }
    
    public static List<Order__c> getOrderItems(Id orderId){
        try{
            String oliRecordType = Schema.getGlobalDescribe().get('Order__c').getDescribe().getRecordTypeInfosByName().get('Order Line Item').getRecordTypeId();
			List<Order__c> orderItemLst = [select id,UnitPrice__c,Product__c,Product__r.Name,Product__r.BusinessUnitType__c,Product__r.ProductCode__c,Quantity__c  from Order__c where Order__c =: orderId AND RecordTypeId = :oliRecordType];
            if(orderItemLst.size() > 0){
                return orderItemLst;
            }
            return null;
        }Catch(Exception e){
            return null;
        }
    }
}