force-app/main/default/objects/Route_Plan__c/Route_Plan__c.object-meta.xml
<CustomObject>
    <label>Route Plan</label>
    <nameField>
        <label>Route Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Route Plan</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Route_Plan__c/fields/ASM__c.field-meta.xml
<CustomField>
    <fullName>ASM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ASM</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Route_Plan</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Route_Plan__c/fields/Dealer_Name__c.field-meta.xml
<CustomField>
    <fullName>Dealer_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dealer Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Route Plan</relationshipLabel>
    <relationshipName>Route_Plan</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Route_Plan__c/fields/Route_Plan__c.field-meta.xml
<CustomField>
    <fullName>Route_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Route Plan</label>
    <referenceTo>Route_Plan__c</referenceTo>
    <relationshipLabel>Route Plan Activity</relationshipLabel>
    <relationshipName>Route_Plan</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Route_Plan__c/recordTypes/Activity.recordType-meta.xml
<RecordType>
    <fullName>Activity</fullName>
    <active>true</active>
    <label>Activity</label>
</RecordType>

force-app/main/default/classes/MapDirectionsController.cls
public class MapDirectionsController {
@AuraEnabled(cacheable=true)
    public static List<Account> getTodayCreatedAccounts() {
        Set<Id> PlanDealerId = new Set<Id>();
        Id activityRecordType = Schema.SObjectType.Route_Plan__c.getRecordTypeInfosByName().get('Activity').getRecordTypeId();
        List<Route_Plan__c> dealerLst = [SELECT Dealer_Name__c,Dealer_Name__r.Name , Dealer_Name__r.ID FROM Route_Plan__c WHERE RecordType.Name = 'Activity' AND Visit_Date__c = TODAY AND ASM__c = :UserInfo.getUserId()];
        for(Route_Plan__c rr : dealerLst){
            if(rr.Dealer_Name__c != null){
                PlanDealerId.add(rr.Dealer_Name__r.ID);
            }
        }
        List<Account> accounts = [SELECT Id, Name, BillingLatitude, BillingLongitude, BillingStreet, BillingCity, BillingState, BillingPostalCode
                                   FROM Account where Id =: PlanDealerId ];
        return accounts;
    }
}