force-app/main/default/objects/Route_Plan__c/Route_Plan__c.object-meta.xml
<CustomObject>
    <label>Route Plan</label>
    <nameField>
        <label>Route Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Route Plan</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Route_Plan__c/fields/CheckInDateTime__c.field-meta.xml
<CustomField>
    <fullName>CheckInDateTime__c</fullName>
    <label>CheckInDateTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Route_Plan__c/fields/Dealer_Name__c.field-meta.xml
<CustomField>
    <fullName>Dealer_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dealer Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Route Plan</relationshipLabel>
    <relationshipName>Route_Plan</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Route_Plan__c/fields/Route_Plan__c.field-meta.xml
<CustomField>
    <fullName>Route_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Route Plan</label>
    <referenceTo>Route_Plan__c</referenceTo>
    <relationshipLabel>Route Plan Activity</relationshipLabel>
    <relationshipName>Route_Plan</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Route_Plan__c/recordTypes/Activity.recordType-meta.xml
<RecordType>
    <fullName>Activity</fullName>
    <active>true</active>
    <label>Activity</label>
</RecordType>

force-app/main/default/classes/ShowDealerLocationCtr.cls
public class ShowDealerLocationCtr {

   
       @AuraEnabled(cacheable=true)
    public static List<Route_Plan__c> getTodayVisitedDealersOnDayEnd() {

        Date systemToday = System.today();
        DateTime dateTimeToday = DateTime.newInstance(systemToday, Time.newInstance(0, 0, 0, 0));
        Date dateToday = dateTimeToday.dateGMT();
        Id activityRecordTypeId = Schema.SObjectType.Route_Plan__c.getRecordTypeInfosByName().get('Activity').getRecordTypeId();
        List<Route_Plan__c> HMCRoutePlaneList = [SELECT Id,Visit_Date__c, Dealer_Name__r.Name, CreatedById, Dealer_Name__r.BillingAddress,Dealer_Name__r.BillingStreet,Dealer_Name__r.BillingCity,Dealer_Name__r.BillingPostalCode,Dealer_Name__r.BillingState,Dealer_Name__r.BillingCountry FROM Route_Plan__c WHERE Visit_Date__c = :systemToday AND CreatedById = :UserInfo.getUserId() AND  RecordTypeId=: activityRecordTypeId AND CheckInDateTime__c !=Null];

        return HMCRoutePlaneList;
    }
}