force-app/main/default/objects/Scheme__c/Scheme__c.object-meta.xml
<CustomObject>
    <label>Scheme</label>
    <nameField>
        <label>Scheme Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schemes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Scheme__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>product2__c</referenceTo>
    <relationshipLabel>Schemes</relationshipLabel>
    <relationshipName>Schemes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Scheme__c/fields/Thumbnail__c.field-meta.xml
<CustomField>
    <fullName>Thumbnail__c</fullName>
    <label>Thumbnail</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Scheme__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>Title</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/SchemeRecordDisplayController.cls
public class SchemeRecordDisplayController {
    
    @AuraEnabled(cacheable=true)
    public Static List<Scheme__c> getAllScheme(){
        List<Scheme__c> schemeListIsPublic = [SELECT Id, Name,Thumbnail__c,Title__c, Start_Date__c,End_Date__c FROM Scheme__c];
        return schemeListIsPublic;    
    }
    
    @AuraEnabled
    public static String getschemedetail(String searchKey){
        Scheme__c sc = [select Id, Name,Product__c, Start_Date__c,Thumbnail__c,Description__c,End_Date__c from Scheme__c where Id =: searchKey LIMIT 1];
        return JSON.serialize(sc);       
    }
}